version: "3.8"
services:
  mongodb:
    build: ./mongo
    container_name: mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: lobby
    ports:
      - 27017:27017
    networks:
      - lobby
    volumes:
      - data_mongo:/data/db
  mysqldb:
    image: mysql
    container_name: mysqldb
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: lobby
      MYSQL_ROOT_PASSWORD: 123123
    ports:
      - 3307:3306
    networks:
      - lobby
    volumes:
      - data_mysql:/var/lib/mysql
      - ./app:/docker-entrypoint-initdb.d
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: app
    restart: unless-stopped
    volumes:
      - ./app:/app
    ports:
      - "3000:3000"
    networks:
      - lobby
    depends_on:
      - mongodb
      - mysqldb
volumes:
  data_mongo:
  data_mysql:
networks:
  lobby:
    driver: bridge
